name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      # - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: git config --global user.email "antonioolvera1995@gmail.com"
      - run: git config --global user.name "antonioolvera1995"          
      # - run: git tag -a 1010 -m "version 1.0"
      # - run: git push origin 1010
      # - run: echo $(git tag)
      - run: bash version.bash


      
      